version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: gen
    ports:
      - "5019-5020:5020"
    deploy:
      mode: replicated
      replicas: 2
  web2:
    build: ./quote_disp
    container_name: disp
    ports:
      - "5021:5021"
    depends_on:
      - web1